name: surf_flutter_summer_school_24
description: "Surf Flutter Summer School '24"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  elementary: ^3.0.0
  flutter:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true


  assets:
    - assets/png/
    - assets/light/png/
    - assets/dark/png/
